export const WAIVER_TEXT = `Releases A Little Taste of Everything DBA MILL CREEK URBAN FARM, a non-profit corporation organized and existing under the laws of the State of Pennsylvania and each of its directors, officers, and agents. The volunteer desires to provide services for MILL CREEK URBAN FARM and engage in activities related to serving as a volunteer by performing associated farming duties.

Volunteers understand that the scope of a volunteers' relationship is limited to a volunteer position and MILL CREEK URBAN FARM that no compensation is expected in return for services provided by volunteer. That MILL CREEK URBAN FARM will not provide any benefits traditionally associated with employment to a volunteer; and that the volunteer is responsible for his/her own insurance coverage in the event of personal injury or illness as a result of volunteer services to MILL CREEK URBAN FARM.

(1) Waiver and Release: I, the volunteer, release and forever discharge and hold harmless MILL CREEK URBAN FARM and assigns from any and all liability, claims, demands of whatever kind of nature, either in law or in equity, which arise or may hereafter arise for the services I, the volunteer, provide to MILL CREEK URBAN FARM. I understand and acknowledge that this Waiver and Release discharges MILL CREEK URBAN FARM from any liability or claims that I may have against MILL CREEK URBAN FARM with respect to bodily injury, illness, death, or property damage that may result from the services that I provide to MILL CREEK URBAN FARM or occurring while I am providing volunteer services.

(2) Insurance: Further, I understand that MILL CREEK URBAN FARM does NOT assume any responsibility for or obligation to provide me, the volunteer, with financial or other assistance, including but not limited to medical health or disability benefits or insurance of any nature in the event of such injury or medical expenses incurred by me.

(3) Medical Treatment: I hereby release and forever discharge MILL CREEK URBAN FARM from any claim whatsoever which may arise or may hereafter arise on account of any first-aid treatment or other medical services rendered in connection with any emergency during my tenure as a volunteer with MILL CREEK URBAN FARM.

(4) Photographic Release: I grant and convey to MILL CREEK URBAN FARM all the right, title, and interests in any and all photographs, images, video, or audio recordings of me or my likeness or voice made by MILL CREEK URBAN FARM in connection with my providing volunteer services to MILL CREEK URBAN FARM.

(5) Dress Code, Safety and Respect: As a volunteer with MILL CREEK URBAN FARM, we ask for respect for and to our staff, other volunteers and community members. Protective gear/clothing is highly encouraged for volunteers, including, but not limited to, sunhat, eyewear, boots or protective footwear. Your conduct should always be professional. Foul language and rowdiness will NOT be tolerated. All community questions should be directed to a member of the MILL CREEK URBAN FARM staff.

(6) Other: As a volunteer, I expressly agree that this Waiver and Release is intended to be as broad and inclusive as permitted by the laws of the state of Pennsylvania and that this Release shall be governed by and interpreted in accordance with the laws of the state of Pennsylvania. I agree that in the event that any clause or provision of this Waiver and Release is deemed invalid, the enforceability of the remaining provisions of this release shall not be affected.`
